name: 步步宝

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0 1 1 *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        BBB_bububaoTOKEN: ${{ secrets.BBB_bububaoTOKEN }}	
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.BBB_bububaoTOKEN
        run: |
          npm install
      - name: '运行 【小乐】'
        if: env.BBB_bububaoTOKEN
        run: |
          node Task/bububao.js
        env:
          
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}