name: 多看点

on:
  workflow_dispatch:
  schedule:
     - cron: '*/10 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        DKD_duokandianBODY: ${{ secrets.DKD_duokandianBODY }}	
        DKD_duokandianvideoBODY: ${{ secrets.DKD_duokandianvideoBODY }}	
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.DKD_duokandianBODY
        run: |
          npm install
      - name: '运行 【多看点】'
        if: env.DKD_duokandianBODY
        run: |
          node Task/duokandian.js
        env:
          
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

    
